# stockrs 설정 파일 예시
# 이 파일을 config.toml로 복사하고 실제 값들을 채워넣으세요
# config.toml은 .gitignore에 추가되어 있어 Git에 커밋되지 않습니다

[database]
# 주식 가격 데이터베이스 경로 (5분봉)
stock_db_path = "D:\\db\\stock_price(5min).db"
# 일봉 데이터베이스 경로
daily_db_path = "D:\\db\\stock_price(1day)_with_data.db"
# 주식 가격 데이터베이스 경로 (1분봉)
minute_db_path = "D:\\db\\stock_price(1min).db"
# 거래 결과 저장용 데이터베이스
trading_db_path = "stockrs/trading.db"

[onnx_model]
# ONNX 모델 메타데이터 파일 경로
model_info_path = "data/rust_model_info.json"
# ONNX 모델 파일 경로
model_file_path = "data/best_model.onnx"
# 특징 리스트 파일
features_file_path = "data/features.txt"
# 제외할 종목 리스트
extra_stocks_file_path = "data/extra_stocks.txt"

[korea_investment_api]
# ====== 실제 거래 API 설정 ======
# 실제 거래용 API 키
real_app_key = "YOUR_REAL_APP_KEY_HERE"
real_app_secret = "YOUR_REAL_APP_SECRET_HERE"
# 실제 거래 URL
real_base_url = "https://openapi.koreainvestment.com:9443"
# 실제 거래 계좌번호
real_account_number = "YOUR_REAL_ACCOUNT_NUMBER"
# 실제 거래 종합계좌 여부 (01: 종합계좌, 02: 위탁계좌)
real_account_product_code = "01"

# ====== 모의투자 API 설정 ======
# 모의투자용 API 키  
paper_app_key = "YOUR_PAPER_APP_KEY_HERE"
paper_app_secret = "YOUR_PAPER_APP_SECRET_HERE"
# 모의투자 URL
paper_base_url = "https://openapivts.koreainvestment.com:29443"
# 모의투자 계좌번호
paper_account_number = "YOUR_PAPER_ACCOUNT_NUMBER"
# 모의투자 종합계좌 여부 (01: 종합계좌, 02: 위탁계좌)
paper_account_product_code = "01"

# ====== 정보용 실전 API 설정 ======
# 시세 조회 등 정보 취득용 실전 API (실전/모의 모드에서 공통 사용)
# (주의: 정보 조회만 가능, 실제 거래는 실행되지 않음)
info_app_key = "YOUR_INFO_APP_KEY_HERE"
info_app_secret = "YOUR_INFO_APP_SECRET_HERE" 
# 실전 API URL (정보 조회용)
info_base_url = "https://openapi.koreainvestment.com:9443"
# 실전 계좌번호 (조회용으로만 사용)
info_account_number = "YOUR_INFO_ACCOUNT_NUMBER"
# 실전 종합계좌 여부
info_account_product_code = "01"

[trading]
# 기본 실행 모드 (real/paper/backtest)
# real: 실전거래API + 정보API + DB, paper: 모의API + 정보API + DB, backtest: DB + DB + DB
default_mode = "backtest"
# 최대 포지션 수
max_positions = 5
# 포지션당 최대 금액 (원)
max_position_amount = 1000000
# 손절매 비율 (%)
stop_loss_ratio = 3.0
# 백테스팅 초기 자본금 (원)
initial_capital = 10000000

[backtest]
# ====== 백테스팅 거래 비용 설정 ======
# 매수 시 수수료율 (%)
buy_fee_rate = 0.022
# 매도 시 수수료율 (%)
sell_fee_rate = 0.022
# 매수 시 슬리피지율 (%)
buy_slippage_rate = 0.5
# 매도 시 슬리피지율 (%)
sell_slippage_rate = 0.5

[joonwoo]
# ====== Joonwoo 모델 전용 설정 ======
# 손절매 비율 (%)
stop_loss_pct = 1.0
# 익절매 비율 (%)
take_profit_pct = 2.0
# 추가 손절매 비율 (절반 매도 후 트레일링 스탑) (%)
trailing_stop_pct = 0.7
# 매수 시점 (24시간 형식)
entry_time = "09:30:00"
# 강제 정리 시점 (24시간 형식)
force_close_time = "12:00:00"
# 매수 시 사용할 자산 비율 (%)
entry_asset_ratio = 90.0

[time_management]
# trading_dates.txt 파일 경로
trading_dates_file_path = "data/samsung_1day_dates.txt"
# 시장 휴무일 파일 경로 (연도별 파일 사용)
market_close_file_path = "data/market_close_day_{}.txt"
# 이벤트 체크 간격 (초)
event_check_interval = 30

# ====== 작동 기간 설정 ======
# 프로그램 작동 시작 날짜 (YYYYMMDD 형식)
# 백테스팅: 백테스트 시작일, 실전/모의: 거래 시작일
start_date = "20240101"
# 프로그램 작동 종료 날짜 (YYYYMMDD 형식) 
# 백테스팅: 백테스트 종료일, 실전/모의: 거래 종료일
end_date = "20240621"

[market_hours]
# 데이터 준비 시작 시간 (24시간 형식)
data_prep_time = "08:30:00"
# 거래 시작 시간 (24시간 형식)
trading_start_time = "09:00:00"
# 거래 종료 시간 (24시간 형식)
trading_end_time = "15:20:00"
# 마지막 업데이트 시간 (24시간 형식)
last_update_time = "15:29:00"
# 장 종료 시간 (24시간 형식)
market_close_time = "15:30:00"

[logging]
# 로그 레벨 (error, warn, info, debug, trace)
level = "info" 